/**
 * Adapter manager — resolves and manages the active execution adapter.
 *
 * Phase 46: Model-backed execution adapter boundary.
 *
 * This module provides:
 * - Explicit adapter resolution from configuration
 * - Adapter lifecycle management (create, check, inspect)
 * - Adapter status tracking with structured errors
 *
 * It does NOT:
 * - Auto-detect configuration from environment variables
 * - Fallback silently to stub if model is misconfigured
 * - Cache or pool connections
 * - Run background health checks
 *
 * Configuration is explicit and injected. Availability is checked on demand.
 */

import type { AgentExecutionAdapter } from "./adapter.js";
import { StubExecutionAdapter } from "./adapter.js";
import type {
  AdapterAvailability,
  AdapterKind,
  AdapterStatus,
  AdapterConfigError,
  AdapterResolutionResult,
  OpenAIAdapterConfig,
} from "./adapter-config.js";
import {
  validateOpenAIConfig,
  buildAdapterStatus,
  ALL_ADAPTER_KINDS,
} from "./adapter-config.js";
import { OpenAIExecutionAdapter, checkOpenAIAvailability } from "./openai-adapter.js";
import type { FetchFn } from "./openai-adapter.js";

/* ------------------------------------------------------------------ */
/*  Echo test adapter (for testing real adapter paths without a model)  */
/* ------------------------------------------------------------------ */

/**
 * Echo test adapter.
 *
 * Returns the task description and context preview as the response.
 * Useful for integration testing without an actual model backend.
 *
 * This is honest: clearly labeled as echo/test adapter, not model-generated.
 */
export class EchoTestAdapter implements AgentExecutionAdapter {
  readonly kind = "echo_test";
  readonly isModelBacked = false;

  async execute(request: import("./types.js").AgentRunRequest): Promise<import("./types.js").AgentRunOutput> {
    const start = Date.now();
    const responseText = [
      `[Echo Test Adapter]`,
      "",
      `Task Kind: ${request.taskKind}`,
      `Task Description: ${request.taskDescription}`,
      `Agent: ${request.agentName} (${request.agentKind})`,
      `Context Chars: ${request.assembledContextText.length}`,
      "",
      "This response is generated by the echo test adapter.",
      "It mirrors the request inputs for testing purposes.",
      "It is NOT model-generated.",
    ].join("\n");
    const durationMs = Date.now() - start;
    return {
      responseText,
      isModelGenerated: false,
      adapterKind: "echo_test",
      durationMs,
    };
  }
}

/* ------------------------------------------------------------------ */
/*  Adapter resolution                                                 */
/* ------------------------------------------------------------------ */

/** Options for resolving an adapter. */
export interface ResolveAdapterOptions {
  /** Desired adapter kind. */
  readonly kind: AdapterKind | string;
  /** OpenAI adapter config (required when kind is "openai_compatible"). */
  readonly openaiConfig?: OpenAIAdapterConfig;
  /** Override fetch function (for testing). */
  readonly fetchFn?: FetchFn;
  /** Whether to skip the availability check. */
  readonly skipAvailabilityCheck?: boolean;
}

/**
 * Resolve an execution adapter from explicit configuration.
 *
 * This is the main entry point for adapter creation.
 *
 * Flow:
 * 1. Validate the requested kind
 * 2. Validate kind-specific config
 * 3. Create the adapter instance
 * 4. Optionally check availability
 * 5. Return structured result
 *
 * No fallback. No auto-detection. If config is wrong, return an error.
 */
export async function resolveAdapter(
  options: ResolveAdapterOptions,
): Promise<AdapterResolutionResult> {
  const { kind } = options;

  // Stub adapter — always available, no config needed
  if (kind === "stub") {
    const adapter = new StubExecutionAdapter();
    const status = buildAdapterStatus(adapter, "configured_available", {
      label: "Stub (Deterministic / Demo)",
    });
    return { ok: true, adapter, status, error: null };
  }

  // Echo test adapter — always available, no config needed
  if (kind === "echo_test") {
    const adapter = new EchoTestAdapter();
    const status = buildAdapterStatus(adapter, "configured_available", {
      label: "Echo Test (Deterministic)",
    });
    return { ok: true, adapter, status, error: null };
  }

  // OpenAI-compatible adapter
  if (kind === "openai_compatible") {
    return resolveOpenAIAdapter(options);
  }

  // Unknown kind
  const status = buildAdapterStatus(
    { kind: String(kind), isModelBacked: false, execute: () => Promise.reject(new Error("unsupported")) },
    "unsupported",
  );
  return {
    ok: false,
    adapter: null,
    status,
    error: {
      kind: "unsupported_kind",
      message: `Unsupported adapter kind: "${kind}". Known kinds: ${ALL_ADAPTER_KINDS.join(", ")}.`,
      details: [],
    },
  };
}

/* ------------------------------------------------------------------ */
/*  OpenAI adapter resolution                                          */
/* ------------------------------------------------------------------ */

async function resolveOpenAIAdapter(
  options: ResolveAdapterOptions,
): Promise<AdapterResolutionResult> {
  const { openaiConfig, fetchFn, skipAvailabilityCheck } = options;

  // No config provided
  if (!openaiConfig) {
    return {
      ok: false,
      adapter: null,
      status: buildAdapterStatus(
        { kind: "openai_compatible", isModelBacked: true, execute: () => Promise.reject(new Error("not configured")) },
        "not_configured",
        { label: "OpenAI-Compatible API" },
      ),
      error: {
        kind: "not_configured",
        message: "OpenAI-compatible adapter requires configuration (baseUrl, apiKey, model).",
        details: ["Provide openaiConfig with baseUrl, apiKey, and model."],
      },
    };
  }

  // Validate config
  const validationErrors = validateOpenAIConfig(openaiConfig);
  if (validationErrors.length > 0) {
    return {
      ok: false,
      adapter: null,
      status: buildAdapterStatus(
        { kind: "openai_compatible", isModelBacked: true, execute: () => Promise.reject(new Error("invalid config")) },
        "not_configured",
        { label: "OpenAI-Compatible API", modelName: openaiConfig.model },
      ),
      error: {
        kind: "invalid_config",
        message: `Invalid OpenAI adapter configuration: ${validationErrors.join("; ")}`,
        details: validationErrors,
      },
    };
  }

  // Create adapter
  const adapter = new OpenAIExecutionAdapter(openaiConfig, fetchFn);

  // Check availability (optional)
  if (!skipAvailabilityCheck) {
    const check = await checkOpenAIAvailability(openaiConfig, fetchFn);
    const availability: AdapterAvailability = check.available
      ? "configured_available"
      : "configured_unavailable";
    const status = buildAdapterStatus(adapter, availability, {
      modelName: openaiConfig.model,
      baseUrl: openaiConfig.baseUrl,
      lastCheckedAt: new Date().toISOString(),
      lastError: check.error,
      label: openaiConfig.label ?? `OpenAI-compatible (${openaiConfig.model})`,
    });

    if (!check.available) {
      return {
        ok: false,
        adapter: null,
        status,
        error: {
          kind: "unavailable",
          message: `OpenAI-compatible backend is not reachable: ${check.error ?? "unknown error"}.`,
          details: check.error ? [check.error] : [],
        },
      };
    }

    return { ok: true, adapter, status, error: null };
  }

  // Skip availability check — assume configured_available
  const status = buildAdapterStatus(adapter, "configured_available", {
    modelName: openaiConfig.model,
    baseUrl: openaiConfig.baseUrl,
    label: openaiConfig.label ?? `OpenAI-compatible (${openaiConfig.model})`,
  });

  return { ok: true, adapter, status, error: null };
}

/* ------------------------------------------------------------------ */
/*  Refresh adapter status                                             */
/* ------------------------------------------------------------------ */

/**
 * Refresh the availability status of an existing adapter.
 *
 * This is a lightweight re-check. It does NOT recreate the adapter.
 */
export async function refreshAdapterStatus(
  adapter: AgentExecutionAdapter,
  options?: {
    openaiConfig?: OpenAIAdapterConfig;
    fetchFn?: FetchFn;
  },
): Promise<AdapterStatus> {
  if (adapter.kind === "stub") {
    return buildAdapterStatus(adapter, "configured_available", {
      label: "Stub (Deterministic / Demo)",
      lastCheckedAt: new Date().toISOString(),
    });
  }

  if (adapter.kind === "echo_test") {
    return buildAdapterStatus(adapter, "configured_available", {
      label: "Echo Test (Deterministic)",
      lastCheckedAt: new Date().toISOString(),
    });
  }

  if (adapter.kind === "openai_compatible" && options?.openaiConfig) {
    const check = await checkOpenAIAvailability(options.openaiConfig, options.fetchFn);
    const availability: AdapterAvailability = check.available
      ? "configured_available"
      : "configured_unavailable";
    return buildAdapterStatus(adapter, availability, {
      modelName: options.openaiConfig.model,
      baseUrl: options.openaiConfig.baseUrl,
      lastCheckedAt: new Date().toISOString(),
      lastError: check.error,
      label: options.openaiConfig.label ?? `OpenAI-compatible (${options.openaiConfig.model})`,
    });
  }

  return buildAdapterStatus(adapter, "unsupported", {
    lastCheckedAt: new Date().toISOString(),
    lastError: `Cannot refresh status for adapter kind: ${adapter.kind}`,
  });
}
